#
# Welcome to the VALORANCE Configuration File.
#
# The configuration options below allow you to configure your VALORANCE plugin
# to best fit the needs of you and your server. Editing the values found below
# allow you to change settings WITHOUT having to modify the source code in any
# way. If you so choose, the plugin is available on GitHub as a free, complete
# open-source project, but you will have to build the plugin yourself once you
# change the source code.
#

match-options:
  # default: the default settings will apply to any game where you don't specify
  # a specific preset option, or where you choose the "default" preset.
  default:
    # choose whether or not to allow multiple of the same agent on the same team.
    allow-duplicate-agents: false
    # add a list of agents to block from selection.
    restricted-agents:
    # - follow this format to add agents to the list below.
    # - like this!
    infinite-credits: false
    infinite-abilities: false
    infinite-ammo: false
    ignore-shopping-restrictions: false

    #The following options pertain to individual rounds.
    round:
      pregame-time: 25
      time: 100
      postround-time: 7

    first-round:
      pregame-time: 45
      time: 100
      postround-time: 7


